---
# Start Jenkins container using persistent /var/jenkins_home

- name: Check if Jenkins container exists
  community.docker.docker_container_info:
    name: jenkins
  register: jenkins_status
  ignore_errors: true

- name: Run Jenkins container with persistent volume and SSH key access
  community.docker.docker_container:
    name: jenkins
    image: jenkins/jenkins:lts-jdk21
    state: started
    restart_policy: always
    published_ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "{{ jenkins_data_dir }}:/var/jenkins_home"
      - "{{ jenkins_data_dir }}/.ssh/id_rsa:/var/jenkins_home/.ssh/id_rsa:ro"
      - "{{ jenkins_data_dir }}/.ssh/id_rsa.pub:/var/jenkins_home/.ssh/id_rsa.pub:ro"
      - "{{ jenkins_data_dir }}/.ssh/known_hosts:/var/jenkins_home/.ssh/known_hosts:ro"
    user: root
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  when: >
    jenkins_status.container is not defined
    or jenkins_status.container is none
    or jenkins_status.container.State.Status != 'running'

- name: Fix permissions of .ssh directory inside Jenkins container
  community.docker.docker_container_exec:
    container: jenkins
    command: >
      bash -c "chmod 700 /var/jenkins_home/.ssh &&
               chmod 600 /var/jenkins_home/.ssh/id_rsa"
  register: ssh_perm_fix
  changed_when: false
  ignore_errors: true
