---
# Final configuration steps for Jenkins

# Optional: Wait a moment to allow init scripts to run
- name: Pause briefly for Jenkins init script to apply
  ansible.builtin.pause:
    seconds: 10

- name: Wait for Jenkins to become responsive
  ansible.builtin.uri:
    url: http://localhost:8080/login
    status_code: 200
    return_content: false
  register: jenkins_status
  retries: 10
  delay: 15
  until: jenkins_status.status == 200
