---
- name: Install required system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Install Docker using official install script
  shell: curl -fsSL https://get.docker.com | sh
  args:
    executable: /bin/bash

- name: Ensure Docker service is running
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true

- name: Pull Jenkins LTS Docker image
  docker_image:
    name: jenkins/jenkins
    tag: lts
    source: pull

- name: Ensure Jenkins home directory exists with correct permissions
  file:
    path: /var/jenkins_home
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

- name: Run Jenkins container
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    state: started
    restart_policy: always
    published_ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home:/var/jenkins_home