---
# Main Jenkins role task entrypoint

# 1. Ensure Jenkins container is running
- name: Ensure Jenkins container is running
  ansible.builtin.include_tasks: container.yml

# 2. Include SSH key setup for Jenkins agent access
- name: Include SSH key setup for Jenkins agent access
  ansible.builtin.include_tasks: ssh.yml

# 3. Include filesystem and Groovy init script preparation
- name: Include filesystem and Groovy init script preparation
  ansible.builtin.include_tasks: prepare.yml

# 4. Include plugins.txt rendering and hash calculation
- name: Include plugins.txt rendering and hash calculation
  ansible.builtin.include_tasks: plugins.yml

# 5. Include final plugin installation and OCI SDK setup
- name: Include final plugin installation and OCI SDK setup
  ansible.builtin.include_tasks: finalize.yml
