---
# Main Jenkins role task entrypoint

- name: Run Jenkins container with persistent data
  ansible.builtin.include_tasks: container.yml

- name: Install tools inside Jenkins container
  ansible.builtin.include_tasks: tools.yml
