---
# Main Jenkins role task entrypoint

- name: Prepare Jenkins data directory
  ansible.builtin.include_tasks: prepare.yml
  tags: jenkins

- name: Run Jenkins container with persistent data
  ansible.builtin.include_tasks: container.yml
  tags: jenkins

- name: Install tools inside Jenkins container
  ansible.builtin.include_tasks: tools.yml
  tags: jenkins

- name: Setup SSH access for Jenkins
  ansible.builtin.include_tasks: ssh.yml
  tags: ssh

- name: Set up SSH access for Jenkins to deploy targets
  ansible.builtin.include_tasks: ssh.yml
  tags: jenkins
