---
# Install Jenkins plugins directly

- name: Install Jenkins plugins via jenkins-plugin-cli
  community.docker.docker_container_exec:
    container: jenkins
    command: >
      sh -c "jenkins-plugin-cli --plugins < /plugins.txt"
  register: plugin_install_result

- name: Restart Jenkins to apply plugin changes
  community.docker.docker_container:
    name: jenkins
    state: started
    restart: true
  when: plugin_install_result.rc | default(1) == 0

