---
# Prepare Jenkins environment: create persistent data directory and SSH trust

- name: Ensure Jenkins data directory exists
  ansible.builtin.file:
    path: "{{ jenkins_data_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Ensure .ssh directory exists inside Jenkins data dir
  ansible.builtin.file:
    path: "{{ jenkins_data_dir }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'

- name: Temporarily relax permissions for known_hosts write
  ansible.builtin.file:
    path: "{{ jenkins_data_dir }}/.ssh"
    mode: '0755'
  become: true

- name: Approve SSH host key for UAT server (persisted in mounted volume)
  ansible.builtin.known_hosts:
    name: "oci.uat.pauloazedo.dev"
    key: "{{ lookup('pipe', 'ssh-keyscan -H oci.uat.pauloazedo.dev') }}"
    path: "{{ jenkins_data_dir }}/.ssh/known_hosts"
    state: present
  become: true

- name: Restore strict permissions after host key write
  ansible.builtin.file:
    path: "{{ jenkins_data_dir }}/.ssh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'
  become: true

- name: Set correct ownership on known_hosts file
  ansible.builtin.file:
    path: "{{ jenkins_data_dir }}/.ssh/known_hosts"
    owner: 1000
    group: 1000
    mode: '0644'
  become: true
