---
# Prepare Jenkins environment: create persistent data directory only

- name: Ensure Jenkins data directory exists
  ansible.builtin.file:
    path: "{{ jenkins_data_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
