---
# Set Jenkins admin credentials directly from group_vars/all.secrets.yml and inject them into Jenkins configuration

# Step 1: Set Jenkins admin username fact on the target server
- name: Set Jenkins admin username fact on the target server
  set_fact:
    jenkins_admin_user: "{{ jenkins_admin_user }}"

# Step 2: Set Jenkins admin password fact on the target server
- name: Set Jenkins admin password fact on the target server
  set_fact:
    jenkins_admin_pass: "{{ jenkins_admin_pass }}"

# Step 3: Set GitHub token fact on the target server
- name: Set GitHub token fact on the target server
  set_fact:
    github_token: "{{ github_token }}"
