---
# Generate and distribute SSH key for Jenkins to access remote nodes

- name: Ensure .ssh directory exists for devops user
  ansible.builtin.file:
    path: /home/devops/.ssh
    state: directory
    owner: devops
    group: devops
    mode: '0700'

- name: Generate SSH keypair for Jenkins if it doesn't exist
  ansible.builtin.command:
    cmd: >
      ssh-keygen -t rsa -b 4096
      -f /home/devops/.ssh/id_rsa_jenkins_ansible
      -N "" -C "jenkins@uat"
  args:
    creates: /home/devops/.ssh/id_rsa_jenkins_ansible
  become: true
  become_user: devops

- name: Read Jenkins public key content
  ansible.builtin.slurp:
    src: /home/devops/.ssh/id_rsa_jenkins_ansible.pub
  register: jenkins_ssh_pubkey
  failed_when: >
    jenkins_ssh_pubkey is not defined or
    jenkins_ssh_pubkey.content is not defined

- name: Install Jenkins public key on all target hosts
  ansible.posix.authorized_key:
    user: devops
    state: present
    key: "{{ jenkins_ssh_pubkey.content | b64decode }}"
  become: true
