---
# Setup SSH access for Jenkins

- name: Ensure Jenkins .ssh directory exists with correct permissions
  ansible.builtin.file:
    path: "{{ jenkins_data_dir }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'

- name: Generate SSH keypair for Jenkins if not present
  community.crypto.openssh_keypair:
    path: "{{ jenkins_data_dir }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    mode: '0600'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    regenerate: never  # only generate if not present

- name: Read generated Jenkins public key (remote)
  ansible.builtin.slurp:
    src: "{{ jenkins_data_dir }}/.ssh/id_rsa.pub"
  register: jenkins_pub_key

- name: Add Jenkins public key to UAT server authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ jenkins_pub_key['content'] | b64decode }}"
    manage_dir: true
