---
# Install Python, Ansible, OCI SDK, Node.js and npm inside Jenkins container

- name: Install Python, pip, Ansible, OCI SDK, Node.js, npm, and rsync inside Jenkins container
  community.docker.docker_container_exec:
    container: "{{ jenkins_container_name }}"
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y python3-venv python3-pip rsync curl gnupg &&
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&
        apt-get install -y nodejs &&
        python3 -m venv /home/jenkins/venv &&
        /home/jenkins/venv/bin/pip install --upgrade pip &&
        /home/jenkins/venv/bin/pip install ansible oci
      "

# Approve SSH host key inside Jenkins container (writing directly to mounted volume)
- name: Approve SSH host key inside Jenkins container
  community.docker.docker_container_exec:
    container: "{{ jenkins_container_name }}"
    command: >
      bash -c "mkdir -p /var/jenkins_home/.ssh &&
               ssh-keyscan -H oci.uat.pauloazedo.dev >> /var/jenkins_home/.ssh/known_hosts"
