prod_site_image: "iad.ocir.io/pauloazedo/prod-site:latest"

# These must match the proxy_pass ports in prod-https.conf.j2
prod_site_green_port: 3100
prod_site_blue_port: 3200

prod_site_green_container: "prod_site_green"
prod_site_blue_container: "prod_site_blue"
