---
# Common setup tasks for all servers

- name: Ensure Python 3.7+ is installed
  ansible.builtin.package:
    name: python3
    state: present
  when: ansible_facts.python.version.major < 3 or
        (ansible_facts.python.version.major == 3 and ansible_facts.python.version.minor < 7)

- name: Set Python 3 as the default interpreter
  ansible.builtin.alternatives:
    name: python
    path: /usr/bin/python3

- name: Install base packages
  ansible.builtin.package:
    name:
      - git
      - curl
      - unzip
      - wget
      - ca-certificates
      - gnupg
    state: present

- name: Remove podman-docker shim (conflicts with Docker CE)
  ansible.builtin.package:
    name: podman-docker
    state: absent

- name: Add Docker CE YUM repository for OL9 ARM
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/9/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: true

- name: Install Docker CE and CLI (ARM64)
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Enable and start Docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Install docker Python SDK via pip
  ansible.builtin.pip:
    name: docker
    executable: pip3

- name: Install OCI CLI using Oracle script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
    dest: /tmp/oci-cli-install.sh
    mode: '0755'

- name: Run OCI CLI installer
  ansible.builtin.command: bash /tmp/oci-cli-install.sh --accept-all-defaults
  args:
    creates: /home/devops/bin/oci
  become: true
  become_user: devops

- name: Verify OCI CLI installation
  ansible.builtin.command: /home/devops/bin/oci --version
  register: oci_cli_version
  changed_when: false
