---
# Handlers for NGINX role

- name: Reload NGINX
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Restart NGINX
  ansible.builtin.service:
    name: nginx
    state: restarted
