# Default values for Jenkins role

# Jenkins Docker image
jenkins_image: jenkins/jenkins
jenkins_image_tag: lts

# Jenkins ports
jenkins_http_port: 8080
jenkins_agent_port: 50000

# Jenkins data volume (fallback if not defined in group_vars)
jenkins_data_dir: "/home/devops/jenkins_data"  # Default if not overridden

# Jenkins container name
jenkins_container_name: jenkins

# Jenkins healthcheck path
jenkins_healthcheck_url: "http://localhost:{{ jenkins_http_port }}/login"
