---
# ansible/group_vars/all.secrets.yml
# Contains sensitive data to be injected into playbooks

############################################################
# Jenkins Admin Credentials
############################################################
jenkins_admin_user: "devops"  # Replace with your Jenkins admin username
jenkins_admin_pass: "@Jenkins123"  # Replace with your Jenkins admin pass word

############################################################
# OCIR Token (used for docker login)
############################################################
ocir_token: "ocid1.vaultsecret.oc1.iad.amaaaaaap2qn7oiahzfy7zvzll23egu5ba2e5q6qghjbidzew3zrus6tf7lq"  # Existing OCIR token

############################################################
# GitHub Token (used in Jenkins CI pipeline)
############################################################
github_token: "Z2hwX2xxVnBiMFg3dHRDbzFheDVRYmltSFNweEhKckJNaTJCeHRhVA=="  # Replace with your actual GitHub token