---
# Install and configure Fail2Ban on Oracle Linux 9

- name: Install Fail2Ban
  ansible.builtin.dnf:
    name: fail2ban
    state: present

- name: Deploy custom jail.local using templated settings
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban

- name: Enable and start Fail2Ban service
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: started
