---
# UAT Site Deployment Entry Point

- name: Ensure Docker is installed on UAT
  ansible.builtin.include_role:
    name: docker

- name: Check if already logged into OCIR
  ansible.builtin.command: docker info
  register: docker_info_check
  failed_when: false
  changed_when: false

- name: Login to OCIR (if not already logged in)
  ansible.builtin.command:
    cmd: >
      docker login iad.ocir.io
      -u {{ ocir_user }}
      -p {{ ocir_token }}
  when: docker_info_check.stdout is not search('Username: {{ ocir_user }}')
  no_log: true
  changed_when: false

- name: Stop and remove existing UAT site container (if any)
  community.docker.docker_container:
    name: "{{ uat_site_container }}"
    state: absent
    force_kill: true

- name: Force pull UAT site image from OCI
  community.docker.docker_image:
    name: "{{ uat_site_image }}"
    source: pull
    force_source: true
  register: uat_image_pull
  failed_when: false
  ignore_errors: true

- name: Check if UAT image exists locally (tag verification)
  community.docker.docker_image_info:
    name: "{{ uat_site_image }}"
  register: uat_local_image_info
  failed_when: false
  changed_when: false

- name: Set image availability flag
  ansible.builtin.set_fact:
    uat_image_available: >-
      {{ ('Image is up to date' in (uat_image_pull.msg | default('')))
         or ('Downloaded newer image' in (uat_image_pull.msg | default('')))
         or (uat_image_pull.changed | default(false))
         or (
           uat_local_image_info.images is defined
           and uat_local_image_info.images
           | selectattr('RepoTags', 'defined')
           | selectattr('RepoTags', 'contains', uat_site_image)
           | list
           | length > 0
         )
      }}

- name: Show pull result
  ansible.builtin.debug:
    var: uat_image_pull.msg

- name: Show UAT image availability flag
  ansible.builtin.debug:
    var: uat_image_available

- name: Show matching images (for verification)
  ansible.builtin.debug:
    msg: >-
      {{
        uat_local_image_info.images
        | selectattr('RepoTags', 'defined')
        | selectattr('RepoTags', 'contains', uat_site_image)
        | list
      }}
  when: uat_local_image_info.images is defined

- name: Include task to run real app if image is available
  ansible.builtin.import_tasks: run-real.yml
  when: uat_image_available | default(false)

- name: Include fallback cleanup tasks
  ansible.builtin.import_tasks: cleanup.yml
  when: uat_image_available is defined and not uat_image_available
