# ansible/roles/uat_site/tasks/run-real.yml
---

- name: Run UAT site container (real app)
  community.docker.docker_container:
    name: "{{ uat_site_container }}"
    image: "{{ uat_site_image }}"
    restart_policy: always
    published_ports:
      - "{{ uat_site_port }}:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    recreate: true
    state: started
