---
# ansible/roles/prod_site/tasks/check_images.yml
# Pull latest versioned blue/green images from OCIR and check availability

#####################################################################
# Step 1: Try pulling green image
#####################################################################
- name: "Try to pull green image (tag: {{ latest_prod_site_tag }})"
  community.docker.docker_image:
    name: "{{ prod_site_green_image }}"
    source: pull
  register: green_image_check
  failed_when: false
  ignore_errors: true
  tags:
    - fallback

#####################################################################
# Step 2: Try pulling blue image
#####################################################################
- name: "Try to pull blue image (tag: {{ latest_prod_site_tag }})"
  community.docker.docker_image:
    name: "{{ prod_site_blue_image }}"
    source: pull
  register: blue_image_check
  failed_when: false
  ignore_errors: true
  tags:
    - fallback

#####################################################################
# Step 3: Set image availability flags
#####################################################################
- name: Set image availability flags for blue/green
  ansible.builtin.set_fact:
    green_image_available: >-
      {{ 'Image is up to date' in green_image_check.msg
         or 'Downloaded newer image' in green_image_check.msg }}
    blue_image_available: >-
      {{ 'Image is up to date' in blue_image_check.msg
         or 'Downloaded newer image' in blue_image_check.msg }}
  tags:
    - fallback

#####################################################################
# Step 4: Log results
#####################################################################
- name: Show image availability results
  ansible.builtin.debug:
    msg:
      - "Latest prod-site tag: {{ latest_prod_site_tag }}"
      - "Green image available: {{ green_image_available | default(false) }}"
      - "Blue image available:  {{ blue_image_available | default(false) }}"
  tags:
    - fallback
