# ansible/roles/prod_site/tasks/check_images.yml
# Pull latest versioned blue/green images from OCIR and check availability

#####################################################################
# Step 1: Try pulling green image
#####################################################################
- name: "Try to pull green image (tag: {{ latest_prod_site_tag }})"
  community.docker.docker_image:
    name: "{{ prod_site_green_image }}"
    source: pull
  register: green_image_check
  failed_when: false
  ignore_errors: true

#####################################################################
# Step 2: Try pulling blue image
#####################################################################
- name: "Try to pull blue image (tag: {{ latest_prod_site_tag }})"
  community.docker.docker_image:
    name: "{{ prod_site_blue_image }}"
    source: pull
  register: blue_image_check
  failed_when: false
  ignore_errors: true

#####################################################################
# Step 3: Inspect local image presence
#####################################################################
- name: Inspect local green image
  community.docker.docker_image_info:
    name: "{{ prod_site_green_image }}"
  register: green_image_info
  failed_when: false
  changed_when: false

- name: Inspect local blue image
  community.docker.docker_image_info:
    name: "{{ prod_site_blue_image }}"
  register: blue_image_info
  failed_when: false
  changed_when: false

- name: Set image availability flags for blue/green
  ansible.builtin.set_fact:
    green_image_available: "{{ green_image_info.images | length > 0 }}"
    blue_image_available: "{{ blue_image_info.images | length > 0 }}"

#####################################################################
# Step 4: Log results
#####################################################################
- name: Show image availability results
  ansible.builtin.debug:
    msg:
      - "Latest prod-site tag: {{ latest_prod_site_tag }}"
      - "Green image available: {{ green_image_available }}"
      - "Blue image available:  {{ blue_image_available }}"
