# ansible/roles/prod_site/tasks/docker-prune.yml
---
# Prune unused Docker data on the PROD server

- name: Prune unused Docker images and build cache
  ansible.builtin.shell: docker system prune -af --volumes
  args:
    executable: /bin/bash
  register: docker_prune_output
  changed_when: docker_prune_output.stdout != ""
  failed_when: false
  tags: [prod_site, cleanup]

- name: Show Docker prune result
  ansible.builtin.debug:
    msg: "{{ docker_prune_output.stdout_lines | default([]) }}"
  when: docker_prune_output.stdout_lines is defined
  tags: [prod_site, cleanup]
