# ansible/roles/prod_site/tasks/docker-prune.yml
# Final cleanup: Prune unused Docker data from the PROD server

#####################################################################
# Step 1: Perform Docker system prune (images, containers, volumes)
#####################################################################
- name: Prune unused Docker images, containers, volumes and build cache
  ansible.builtin.shell: docker system prune -af --volumes
  args:
    executable: /bin/bash
  register: docker_prune_output
  changed_when: docker_prune_output.stdout != ""
  failed_when: false
  tags:
    - prod_site
    - cleanup

#####################################################################
# Step 2: Display Docker prune output
#####################################################################
- name: Show Docker prune result
  ansible.builtin.debug:
    msg: "{{ docker_prune_output.stdout_lines | default([]) }}"
  when: docker_prune_output.stdout_lines is defined
  tags:
    - prod_site
    - cleanup
