---
- name: Ensure Docker is installed on UAT
  ansible.builtin.include_role:
    name: docker
  tags: always  # this ensures Docker is always ensured regardless of tag

- name: Create placeholder index.html for UAT
  ansible.builtin.copy:
    content: "<html><body><h1>UAT Environment - Awaiting first deployment</h1></body></html>"
    dest: /home/devops/uat_index.html
    owner: devops
    group: devops
    mode: '0644'

- name: Run UAT placeholder container
  community.docker.docker_container:
    name: uat-site
    image: nginx:alpine
    restart_policy: always
    published_ports:
      - "{{ uat_site_port }}:80"
    volumes:
      - /home/devops/uat_index.html:/usr/share/nginx/html/index.html:ro
    state: started
