# ansible/roles/prod_site/tasks/main.yml
# PROD Site Blue/Green Deployment Logic with Fallback

#####################################################################
# Step 1: Ensure Docker is installed on the PROD host
#####################################################################
- name: Ensure Docker is installed
  ansible.builtin.include_role:
    name: docker
  tags: always

#####################################################################
# Step 2: Authenticate with OCIR (Oracle Container Registry)
#####################################################################
- name: Check if already logged into OCIR
  ansible.builtin.command: docker info
  register: docker_info_check
  changed_when: false
  failed_when: false

- name: Login to OCIR (if not already logged in)
  ansible.builtin.command:
    cmd: >
      docker login iad.ocir.io
      -u {{ ocir_user }}
      -p {{ ocir_token }}
  when: docker_info_check.stdout is not search('iad.ocir.io')
  no_log: true
  changed_when: false

#####################################################################
# Step 3: Discover the latest prod-site image tag from OCIR
#####################################################################
- name: Fetch latest prod-site tag from OCIR
  ansible.builtin.shell: |
    set -o pipefail
    curl -s -H "Authorization: Bearer {{ ocir_token }}" \
      https://iad.ocir.io/v2/{{ ocir_namespace }}/prod-site/tags/list |
    jq -r '.tags | sort | reverse | .[0]'
  register: latest_tag_result
  changed_when: false
  failed_when: latest_tag_result.rc != 0 or latest_tag_result.stdout == ""

- name: Set latest tag and define image references
  ansible.builtin.set_fact:
    latest_prod_site_tag: "{{ latest_tag_result.stdout }}"
    prod_site_blue_image: "iad.ocir.io/{{ ocir_namespace }}/prod-site:{{ latest_prod_site_tag }}"
    prod_site_green_image: "iad.ocir.io/{{ ocir_namespace }}/prod-site:{{ latest_prod_site_tag }}"

- name: Show tag being deployed
  ansible.builtin.debug:
    msg: "Deploying prod-site version {{ latest_prod_site_tag }} to blue/green"

#####################################################################
# Step 4: Check image availability
#####################################################################
- name: Check availability of versioned images
  ansible.builtin.include_tasks: check_images.yml
  tags: fallback

#####################################################################
# Step 5: Fallback logic (build and push if image not found)
#####################################################################
- name: Build and push fallback image
  ansible.builtin.include_tasks: run-fallback.yml
  when:
    - force_fallback | default(false)
    - not (blue_image_available | default(false)) and not (green_image_available | default(false))
  tags:
    - fallback
    - force-fallback

#####################################################################
# Step 6: Deploy blue and green containers
#####################################################################
- name: Deploy blue container
  ansible.builtin.include_tasks: run-blue.yml
  when: prod_site_target in ["both", "blue"]

- name: Deploy green container
  ansible.builtin.include_tasks: run-green.yml
  when: prod_site_target in ["both", "green"]

#####################################################################
# Step 7: Cleanup fallback artifacts
#####################################################################
- name: Cleanup fallback for blue
  ansible.builtin.include_tasks: cleanup-blue.yml
  when:
    - prod_site_target in ["both", "blue"]
    - not (blue_image_available | default(false)) and not (green_image_available | default(false))
  tags: fallback

- name: Cleanup fallback for green
  ansible.builtin.include_tasks: cleanup-green.yml
  when:
    - prod_site_target in ["both", "green"]
    - not (blue_image_available | default(false)) and not (green_image_available | default(false))
  tags: fallback

#####################################################################
# Step 8: Final Docker system cleanup
#####################################################################
- name: Final Docker cleanup
  ansible.builtin.import_tasks: docker-prune.yml
  tags: [prod_site, cleanup]
