---
# PROD Site Deployment - Blue/Green with fallback and image labeling

# Step 1: Ensure Docker is installed
- name: Ensure Docker is installed
  ansible.builtin.include_role:
    name: docker
  tags: always

# Step 2: Authenticate to OCIR (if not already logged in)
- name: Check if already logged into OCIR
  ansible.builtin.command: docker info
  register: docker_info_check
  failed_when: false
  changed_when: false

- name: Login to OCIR (if not already logged in)
  ansible.builtin.command:
    cmd: >
      docker login iad.ocir.io
      -u {{ ocir_user }}
      -p {{ ocir_token }}
  when: docker_info_check.stdout is not search('iad.ocir.io')
  no_log: true
  changed_when: false

# Step 3: Try pulling green and blue images from OCIR
- name: Try to pull green image
  community.docker.docker_image:
    name: "{{ prod_site_green_image }}"
    source: pull
  register: green_image_check
  failed_when: false
  ignore_errors: true

- name: Try to pull blue image
  community.docker.docker_image:
    name: "{{ prod_site_blue_image }}"
    source: pull
  register: blue_image_check
  failed_when: false
  ignore_errors: true

# Step 4: Set image availability flags
- name: Set image availability flags
  ansible.builtin.set_fact:
    green_image_available: >-
      {{ ('Image is up to date' in green_image_check.msg)
         or ('Downloaded newer image' in green_image_check.msg) }}
    blue_image_available: >-
      {{ ('Image is up to date' in blue_image_check.msg)
         or ('Downloaded newer image' in blue_image_check.msg) }}

- name: Show green/blue image availability
  ansible.builtin.debug:
    msg: >
      Green: {{ green_image_available | default(false) }},
      Blue: {{ blue_image_available | default(false) }}

# Step 5: Fallback - build, tag, push waiting container if needed
- name: Copy fallback Dockerfile to remote host
  ansible.builtin.copy:
    src: files/prod-waiting.Dockerfile
    dest: /home/devops/prod-waiting.Dockerfile
    owner: devops
    group: devops
    mode: '0644'
  when: not green_image_available and not blue_image_available

- name: Copy fallback NGINX config to remote host
  ansible.builtin.copy:
    src: files/default-waiting.conf
    dest: /home/devops/default-waiting.conf
    owner: devops
    group: devops
    mode: '0644'
  when: not green_image_available and not blue_image_available

- name: Copy fallback HTML to remote host
  ansible.builtin.copy:
    src: files/prod-fallback-index.html
    dest: /home/devops/index.html
    owner: devops
    group: devops
    mode: '0644'
  when: not green_image_available and not blue_image_available

- name: Build fallback PROD image
  community.docker.docker_image:
    name: "prod-waiting"
    tag: "latest"
    source: build
    force_source: true
    build:
      path: /home/devops
      dockerfile: prod-waiting.Dockerfile
      labels:
        org.opencontainers.image.created: "{{ ansible_date_time.iso8601 }}"
        org.opencontainers.image.description: "Fallback PROD site - waiting for Jenkins"
        org.opencontainers.image.source: "ansible"
  when: not green_image_available and not blue_image_available

- name: Tag fallback image for OCIR
  ansible.builtin.command:
    cmd: >
      docker tag prod-waiting:latest {{ prod_site_waiting_image }}
  when: not green_image_available and not blue_image_available
  changed_when: true
  check_mode: false

- name: Push fallback image to OCIR
  ansible.builtin.command:
    cmd: >
      docker push {{ prod_site_waiting_image }}
  when: not green_image_available and not blue_image_available
  changed_when: true
  check_mode: false

# Step 6: Stop and remove existing containers
- name: Stop and remove green container
  community.docker.docker_container:
    name: "{{ prod_site_green_container }}"
    state: absent
    force_kill: true

- name: Stop and remove blue container
  community.docker.docker_container:
    name: "{{ prod_site_blue_container }}"
    state: absent
    force_kill: true

# Step 7: Run green container
- name: Start green container with real image
  community.docker.docker_container:
    name: "{{ prod_site_green_container }}"
    image: "{{ prod_site_green_image }}"
    restart_policy: always
    published_ports:
      - "{{ prod_site_green_port }}:3000"
    recreate: true
    state: started
  when: green_image_available | default(false)

- name: Start green container with fallback image
  community.docker.docker_container:
    name: "{{ prod_site_green_container }}"
    image: "{{ prod_site_waiting_image }}"
    restart_policy: always
    published_ports:
      - "{{ prod_site_green_port }}:3000"
    recreate: true
    state: started
  when: not green_image_available | default(false)

# Step 8: Run blue container
- name: Start blue container with real image
  community.docker.docker_container:
    name: "{{ prod_site_blue_container }}"
    image: "{{ prod_site_blue_image }}"
    restart_policy: always
    published_ports:
      - "{{ prod_site_blue_port }}:3000"
    recreate: true
    state: started
  when: blue_image_available | default(false)

- name: Start blue container with fallback image
  community.docker.docker_container:
    name: "{{ prod_site_blue_container }}"
    image: "{{ prod_site_waiting_image }}"
    restart_policy: always
    published_ports:
      - "{{ prod_site_blue_port }}:3000"
    recreate: true
    state: started
  when: not blue_image_available | default(false)

# Step 9: Remove older fallback images
- name: Remove untagged or older fallback Docker images
  ansible.builtin.shell: |
    set -o pipefail
    docker images --filter=reference='prod-waiting' --format '{{ '{{' }}.Repository{{ '}}' }}:{{ '{{' }}.Tag{{ '}}' }} {{ '{{' }}.ID{{ '}}' }}' |
    grep -v 'prod-waiting:latest' | awk '{print $2}' | xargs -r docker rmi
  args:
    executable: /bin/bash
  register: cleanup_result
  changed_when: cleanup_result.stdout != ""
  failed_when: false
  when: not green_image_available and not blue_image_available

# Step 10: Clean up build files
- name: Remove prod-waiting.Dockerfile
  ansible.builtin.file:
    path: /home/devops/prod-waiting.Dockerfile
    state: absent
  when: not green_image_available and not blue_image_available

- name: Remove default-waiting.conf
  ansible.builtin.file:
    path: /home/devops/default-waiting.conf
    state: absent
  when: not green_image_available and not blue_image_available

- name: Remove prod-fallback-index.html
  ansible.builtin.file:
    path: /home/devops/index.html
    state: absent
  when: not green_image_available and not blue_image_available
