# ansible/roles/prod_site/tasks/query-latest-tag.yml
# Fetch the latest tag from OCIR using skopeo inside the Jenkins container

- name: Query latest OCIR tag from Jenkins container
  community.docker.docker_container_exec:
    container: "{{ jenkins_container_name }}"
    user: root
    command: >
      bash -c 'skopeo list-tags --creds "{{ ocir_user }}:{{ ocir_token }}" docker://{{ prod_site_ocir_repo }} | jq -r ".Tags[]" | sort -V | tail -n1'
  register: latest_tag_output
  changed_when: false
  failed_when: latest_tag_output.rc != 0 or (latest_tag_output.stdout | length) == 0

- name: DEBUG show latest tag from OCIR
  debug:
    msg: "✅ Latest OCIR tag discovered: {{ latest_tag_output.stdout | default('NONE') }}"

- name: Set latest prod-site tag facts
  ansible.builtin.set_fact:
    latest_prod_site_tag: "{{ latest_tag_output.stdout }}"
    prod_site_blue_image: "{{ prod_site_ocir_repo }}:{{ latest_tag_output.stdout }}"
    prod_site_green_image: "{{ prod_site_ocir_repo }}:{{ latest_tag_output.stdout }}"
