#####################################################################
# Step 0: Ensure target is blue or both
#####################################################################
- name: Skip blue deployment if prod_site_target is not 'blue' or 'both'
  ansible.builtin.meta: end_play
  when: prod_site_target not in ['blue', 'both']
  tags: [prod_site, run_blue]

#####################################################################
# Step 1: Remove existing blue container
#####################################################################
- name: Remove existing blue container if present
  community.docker.docker_container:
    name: "{{ prod_site_blue_container }}"
    state: absent
    force_kill: true
  register: blue_cleanup
  ignore_errors: true
  tags: [prod_site, run_blue, cleanup]

- name: Log blue container cleanup result
  ansible.builtin.debug:
    msg: "Removed existing blue container: {{ blue_cleanup.changed }}"
  tags: [prod_site, run_blue, cleanup]

#####################################################################
# Step 2: Run blue container with versioned image
#####################################################################
- name: Run blue container with versioned image ({{ prod_site_image }})
  community.docker.docker_container:
    name: "{{ prod_site_blue_container }}"
    image: "{{ prod_site_image }}"
    restart_policy: always
    published_ports:
      - "{{ prod_site_blue_port }}:3000"
    recreate: true
    state: started
    pull: true
    force_restart: true
    env:
      NEXT_PUBLIC_APP_VERSION: "{{ prod_site_tag }}"
      NEXT_PUBLIC_CLOUD_PROVIDER: "{{ cloud_provider | upper }}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  when: prod_site_image is defined
  tags: [prod_site, run_blue, deploy]
