# ansible/roles/prod_site/tasks/run-green.yml
# Deploy the PROD Green container using the latest tagged image or fallback

#####################################################################
# Step 1: Remove existing green container (if any)
#####################################################################
- name: Remove existing green container if present
  community.docker.docker_container:
    name: "{{ prod_site_green_container }}"
    state: absent
    force_kill: true
  register: green_cleanup
  ignore_errors: true

- name: Log green container cleanup result
  ansible.builtin.debug:
    msg: "Removed existing green container: {{ green_cleanup.changed }}"

#####################################################################
# Step 2: Run green container with versioned image
#####################################################################
- name: Run green container with versioned image ({{ latest_prod_site_tag }})
  community.docker.docker_container:
    name: "{{ prod_site_green_container }}"
    image: "{{ prod_site_green_image }}"
    restart_policy: always
    published_ports:
      - "{{ prod_site_green_port }}:3000"
    recreate: true
    state: started
  when: green_image_available | bool

- name: Persist promoted green version for rollback
  ansible.builtin.copy:
    dest: /home/devops/last-promoted-green.txt
    content: "{{ latest_prod_site_tag }}"
    owner: devops
    group: devops
    mode: '0644'
  when: green_image_available | bool

#####################################################################
# Step 3: Run green container with fallback image (if needed)
#####################################################################
- name: Run green container with fallback image
  community.docker.docker_container:
    name: "{{ prod_site_green_container }}"
    image: "{{ prod_site_waiting_image }}"
    restart_policy: always
    published_ports:
      - "{{ prod_site_green_port }}:3000"
    recreate: true
    state: started
    env: "{{ prod_site_green_env }}"
  when: not (green_image_available | default(false) | bool)
  tags:
    - fallback
