---
# ansible/roles/prod_site/tasks/run-blue.yml
# Deploy the PROD Blue container using the latest tagged image or fallback

#####################################################################
# Step 1: Remove existing blue container (if any)
#####################################################################
- name: Remove existing blue container if present
  community.docker.docker_container:
    name: "{{ prod_site_blue_container }}"
    state: absent
    force_kill: true
  register: blue_cleanup
  ignore_errors: true

- name: Log blue container cleanup result
  ansible.builtin.debug:
    msg: "Removed existing blue container: {{ blue_cleanup.changed }}"

#####################################################################
# Step 2: Run blue container with latest versioned image
#####################################################################
- name: Run blue container with versioned image ({{ latest_prod_site_tag }})
  community.docker.docker_container:
    name: "{{ prod_site_blue_container }}"
    image: "{{ latest_prod_site_image }}"
    restart_policy: always
    published_ports:
      - "{{ prod_site_blue_port }}:3000"
    recreate: true
    state: started
  when: blue_image_available | default(false)

#####################################################################
# Step 3: Run blue container with fallback image (if needed)
#####################################################################
- name: Run blue container with fallback image
  community.docker.docker_container:
    name: "{{ prod_site_blue_container }}"
    image: "{{ prod_site_waiting_image }}"
    restart_policy: always
    published_ports:
      - "{{ prod_site_blue_port }}:3000"
    recreate: true
    state: started
    env: "{{ prod_site_blue_env }}"
  when: not blue_image_available | default(false)
  tags:
    - fallback
