---
# This sets up SSH access from Jenkins to the PROD host server

- name: Ensure ~/.ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Add Jenkins public key to authorized_keys on PROD
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ jenkins_pub_key['content'] | b64decode }}"
    manage_dir: false
