---
# === Fail2Ban Setup ===

- name: Install Fail2Ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
  become: true

- name: Ensure Fail2Ban is enabled and running
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
  become: true

- name: Deploy custom Fail2Ban jail config
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    mode: '0644'
    owner: root
    group: root
    content: |
      [DEFAULT]
      bantime = 3600
      findtime = 600
      maxretry = 5
      backend = systemd

      [sshd]
      enabled = true

      [nginx-http-auth]
      enabled = true

      [nginx-botsearch]
      enabled = true

      [nginx-req-limit]
      enabled = true

      [nginx-noscript]
      enabled = true

      [nginx-nohome]
      enabled = true

      [nginx-404]
      enabled = true
  notify: Restart fail2ban
  become: true

# === IPTABLES RULES ===

- name: Ensure iptables-persistent is installed
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
    update_cache: true
  become: true

- name: Check if HTTP (port 80) rule exists
  ansible.builtin.command: iptables -C INPUT -p tcp --dport 80 -j ACCEPT
  register: check_http_rule
  failed_when: false
  changed_when: false
  become: true

- name: Insert HTTP rule if not present
  ansible.builtin.command: iptables -I INPUT -p tcp --dport 80 -j ACCEPT
  when: check_http_rule.rc != 0
  changed_when: true
  become: true

- name: Check if HTTPS (port 443) rule exists
  ansible.builtin.command: iptables -C INPUT -p tcp --dport 443 -j ACCEPT
  register: check_https_rule
  failed_when: false
  changed_when: false
  become: true

- name: Insert HTTPS rule if not present
  ansible.builtin.command: iptables -I INPUT -p tcp --dport 443 -j ACCEPT
  when: check_https_rule.rc != 0
  changed_when: true
  become: true

- name: Persist iptables rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  changed_when: true
  become: true
