---
# Generate Let's Encrypt certs and update NGINX configs per environment

# Step 1: Define domains and templates per environment
- name: Define domains and templates per environment
  ansible.builtin.set_fact:
    nginx_certbot_domains:
      - domain: "oci.jenkins.pauloazedo.dev"
        template: "jenkins-https.conf.j2"
        filename: "jenkins.conf"
        group: "uat"
      - domain: "oci.uat.pauloazedo.dev"
        template: "uat-https.conf.j2"
        filename: "uat.conf"
        group: "uat"
      - domain: "oci.prod.pauloazedo.dev"
        template: "prod-https.conf.j2"
        filename: "prod.conf"
        group: "prod"

# Step 2: Extract domains relevant to this host (based on group membership)
- name: Extract domains for this host only
  ansible.builtin.set_fact:
    certbot_domains_for_host: >-
      {{
        nginx_certbot_domains
        | selectattr('group', 'in', group_names)
        | list
      }}

# Step 3: Build full list of Certbot paths to delete (if force cleanup is enabled)
- name: Build full list of Certbot paths to delete
  ansible.builtin.set_fact:
    certbot_paths_to_cleanup: >-
      {{
        (certbot_domains_for_host | map(attribute='domain') | map('regex_replace', '^(.*)$', 'live/\\1') | list)
        + (certbot_domains_for_host | map(attribute='domain') | map('regex_replace', '^(.*)$', 'archive/\\1') | list)
        + (certbot_domains_for_host | map(attribute='domain') | map('regex_replace', '^(.*)$', 'renewal/\\1.conf') | list)
      }}
  when: certbot_force_clean | default(false) | bool

# Step 4: Remove previous Certbot state from filesystem (optional)
- name: Clean up previous Certbot state (optional safety for retrying)
  ansible.builtin.file:
    path: "/etc/letsencrypt/{{ item }}"
    state: absent
  loop: "{{ certbot_paths_to_cleanup }}"
  when: certbot_force_clean | default(false) | bool
  tags: certbot

# Step 5: Generate HTTPS certificates using Certbot (only if not already present)
- name: Generate HTTPS certs with Certbot
  ansible.builtin.command:
    cmd: >
      certbot certonly --nginx -d {{ item.domain }}
      --non-interactive --agree-tos
      -m paulo@pauloazedo.dev --redirect
    creates: "/etc/letsencrypt/live/{{ item.domain }}/fullchain.pem"
  register: certbot_result
  changed_when: certbot_result.rc == 0
  failed_when: certbot_result.rc != 0
  loop: "{{ certbot_domains_for_host }}"
  tags: certbot

# Step 6: Replace NGINX HTTP config with HTTPS config
- name: Replace NGINX config with HTTPS version
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "/etc/nginx/conf.d/{{ item.filename }}"
    mode: '0644'
  loop: "{{ certbot_domains_for_host }}"
  tags: certbot

# Step 7: Reload NGINX to apply new HTTPS config
- name: Reload NGINX
  ansible.builtin.service:
    name: nginx
    state: reloaded
  tags: certbot
