---
# Run certbot to generate TLS certs and update configs

- name: Generate HTTPS cert for Jenkins
  ansible.builtin.command:
    cmd: >
      certbot certonly --nginx -d jenkins.pauloazedo.us --non-interactive
      --agree-tos -m pauloazedo@pauloazedo.us --redirect
  register: certbot_jenkins
  changed_when: certbot_jenkins.rc == 0
  failed_when: certbot_jenkins.rc != 0
  tags: certbot
  when: inventory_hostname in groups['uat']

- name: Generate HTTPS cert for UAT
  ansible.builtin.command:
    cmd: >
      certbot certonly --nginx -d uat.pauloazedo.us --non-interactive
      --agree-tos -m pauloazedo@pauloazedo.us --redirect
  register: certbot_uat
  changed_when: certbot_uat.rc == 0
  failed_when: certbot_uat.rc != 0
  tags: certbot
  when: inventory_hostname in groups['uat']

- name: Generate HTTPS cert for PROD
  ansible.builtin.command:
    cmd: >
      certbot certonly --nginx -d prod.pauloazedo.us --non-interactive
      --agree-tos -m pauloazedo@pauloazedo.us --redirect
  register: certbot_prod
  changed_when: certbot_prod.rc == 0
  failed_when: certbot_prod.rc != 0
  tags: certbot
  when: inventory_hostname in groups['prod']

- name: Replace Jenkins config with HTTPS
  ansible.builtin.template:
    src: jenkins-https.conf.j2
    dest: /etc/nginx/conf.d/jenkins.conf
    mode: '0644'
  when: inventory_hostname in groups['uat']

- name: Replace UAT config with HTTPS
  ansible.builtin.template:
    src: uat-https.conf.j2
    dest: /etc/nginx/conf.d/uat.conf
    mode: '0644'
  when: inventory_hostname in groups['uat']

- name: Replace PROD config with HTTPS
  ansible.builtin.template:
    src: prod-https.conf.j2
    dest: /etc/nginx/conf.d/prod.conf
    mode: '0644'
  when: inventory_hostname in groups['prod']

- name: Reload NGINX
  ansible.builtin.service:
    name: nginx
    state: reloaded
