---
# NGINX role main task list

# Step 1: Install and start NGINX
- name: Ensure NGINX is installed
  ansible.builtin.package:
    name: nginx
    state: present

- name: Enable and start NGINX service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

# Step 2: Configure SELinux (allow NGINX to proxy to Docker containers)
- name: Allow NGINX to connect to the network (SELinux)
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

# Step 3: Deploy initial HTTP configs
- name: Deploy Jenkins HTTP config (UAT only)
  ansible.builtin.template:
    src: jenkins-http.conf.j2
    dest: /etc/nginx/conf.d/jenkins.conf
    mode: '0644'
  when: inventory_hostname in groups['uat']

- name: Deploy UAT HTTP config
  ansible.builtin.template:
    src: uat-http.conf.j2
    dest: /etc/nginx/conf.d/uat.conf
    mode: '0644'
  when: inventory_hostname in groups['uat']

- name: Deploy PROD HTTP config
  ansible.builtin.template:
    src: prod-http.conf.j2
    dest: /etc/nginx/conf.d/prod.conf
    mode: '0644'
  when: inventory_hostname in groups['prod']

# Step 4: Ensure certbot is available before running TLS provisioning
- name: Install certbot and certbot-nginx plugin
  ansible.builtin.package:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

# Step 5: Include certbot tasks (modularized in a separate file)
- name: Include Certbot tasks
  ansible.builtin.include_tasks: certbot.yml
  tags: certbot
