---
# Sets up SSH key access and known_hosts for Jenkins to connect to target servers

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ jenkins_data_dir }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"

- name: Generate SSH keypair for Jenkins if not present
  community.crypto.openssh_keypair:
    path: "{{ jenkins_data_dir }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    regenerate: never

- name: Approve SSH host key for UAT server
  ansible.builtin.known_hosts:
    name: oci.uat.pauloazedo.dev
    key: "{{ lookup('pipe', 'ssh-keyscan -H oci.uat.pauloazedo.dev') }}"
    path: "{{ jenkins_data_dir }}/.ssh/known_hosts"
    state: present
  become: true

- name: Approve SSH host key for PROD server
  ansible.builtin.known_hosts:
    name: oci.prod.pauloazedo.dev
    key: "{{ lookup('pipe', 'ssh-keyscan -H oci.prod.pauloazedo.dev') }}"
    path: "{{ jenkins_data_dir }}/.ssh/known_hosts"
    state: present
  become: true

- name: Set correct permissions for known_hosts
  ansible.builtin.file:
    path: "{{ jenkins_data_dir }}/.ssh/known_hosts"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  become: true

- name: Read generated Jenkins public key (remote)
  ansible.builtin.slurp:
    src: "{{ jenkins_data_dir }}/.ssh/id_rsa.pub"
  register: jenkins_pub_key

- name: Add Jenkins public key to current host's authorized_keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ jenkins_pub_key['content'] | b64decode }}"
    manage_dir: true
