---
# Install required packages for Docker
- name: Install prerequisites for Docker
  ansible.builtin.dnf:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: present
    update_cache: true

# Add Docker's official GPG key for Oracle Linux
- name: Add Docker GPG key
  ansible.builtin.rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

# Add Docker repository for Oracle Linux
- name: Add Docker repository for Oracle Linux
  ansible.builtin.yum_repository:
    name: docker
    description: Docker CE Stable - EL8
    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

# Install Docker packages
- name: Install Docker packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

# Ensure Docker service is running
- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

# Add the current Ansible user to the Docker group
- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
