---
- name: Setup NGINX with HTTPS on both UAT and PROD
  hosts: all
  become: true
  vars_files:
    - group_vars/all.secrets.yml
  roles:
    - role: hardening
      tags: hardening
    - role: nginx
      tags: nginx
