---
# ansible/prod.yml
# PROD Infrastructure and Application Deployment (Blue/Green)

- name: Setup base infrastructure and deploy blue/green containers
  hosts: prod
  become: true

  vars_files:
    - group_vars/all.yml
    - group_vars/all.secrets.yml
    - group_vars/{{ cloud_provider }}/{{ cloud_provider }}.yml
    - group_vars/{{ cloud_provider }}/{{ cloud_provider }}.secrets.yml

  # Default target is 'both', can be overridden via --extra-vars
  vars:
    prod_site_target: "both"

  tasks:

    ############################################################
    # Step 1: Base Infrastructure
    ############################################################

    - name: Include bootstrap role
      ansible.builtin.include_role:
        name: "{{ bootstrap_role }}"
      tags: bootstrap

    - name: Include common role
      ansible.builtin.include_role:
        name: "{{ common_role }}"
      tags: common

    - name: Include hardening role
      ansible.builtin.include_role:
        name: "{{ hardening_role }}"
      tags: hardening

    - name: Include docker role
      ansible.builtin.include_role:
        name: "{{ docker_role }}"
      tags: docker

    - name: Include nginx role
      ansible.builtin.include_role:
        name: nginx
      tags:
        - nginx
        - certbot

    - name: Include SSH access role
      ansible.builtin.include_role:
        name: prod_site
      tags: set_ssh_access

    ############################################################
    # Step 2: Deployment (target decided by prod_site_target)
    ############################################################

    - name: Deploy PROD container(s) based on prod_site_target
      ansible.builtin.include_role:
        name: prod_site
      tags: prod_site
