---
# PROD Infrastructure and Application Deployment (Blue/Green)

- name: Setup base infrastructure and deploy both containers by default
  hosts: prod
  become: true

  vars_files:
    - group_vars/all.yml
    - group_vars/all.secrets.yml
    - group_vars/{{ cloud_provider }}/{{ cloud_provider }}.yml
    - group_vars/{{ cloud_provider }}/{{ cloud_provider }}.secrets.yml

  # Set a static default; Jenkins can still override with `-e prod_site_target=blue|green|both`
  vars:
    prod_site_target: "both"

  tasks:
    # Step 1: Infrastructure setup
    - name: Include bootstrap role
      ansible.builtin.include_role:
        name: "{{ bootstrap_role }}"
      tags: bootstrap

    - name: Include common role
      ansible.builtin.include_role:
        name: "{{ common_role }}"
      tags: common

    - name: Include hardening role
      ansible.builtin.include_role:
        name: "{{ hardening_role }}"
      tags: hardening

    - name: Include docker role
      ansible.builtin.include_role:
        name: "{{ docker_role }}"
      tags: docker

    - name: Include nginx role
      ansible.builtin.include_role:
        name: nginx
      tags: nginx

    - name: Include SSH access role
      ansible.builtin.include_role:
        name: prod_site
      tags: set_ssh_access

    # Step 2: Always include prod_site for web container deployment
    - name: Deploy PROD site (blue/green logic inside role)
      ansible.builtin.include_role:
        name: prod_site
      tags: prod_site
