---
# Main Ansible playbook to provision infrastructure for both UAT and PROD environments

# Step 1: Ensure Python 3.7+ is available (needed on clean OCI instances)
- name: Ensure Python 3.7+ is installed
  hosts: all
  become: true
  tasks:
    - name: Install Python 3.7+ if not already installed
      ansible.builtin.raw: |
        if ! command -v python3 &> /dev/null || [[ "$(python3 -V 2>&1 | awk '{print $2}')" < "3.7" ]]; then
          sudo dnf install -y python3
        fi
      changed_when: false

    - name: Set Python 3 as default for Ansible
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3

# Step 2: Setup base system (shared across UAT & PROD)
- name: Setup base infrastructure (UAT & PROD)
  hosts: all
  become: true
  vars_files:
    - group_vars/all.secrets.yml
  roles:
    - role: bootstrap
    - role: common
    - role: hardening
    - role: docker
    - role: nginx

# Step 3: Mount Jenkins persistent block volume (UAT only)
- name: Attach and mount Jenkins block volume
  hosts: uat
  become: true
  roles:
    - role: block_volume

# Step 4: Configure Jenkins (UAT only)
- name: Setup Jenkins (UAT only)
  hosts: uat
  become: true
  vars_files:
    - group_vars/all.secrets.yml
  roles:
    - role: jenkins
      tags: jenkins
  vars:
    profile: DEVOPS

# Step 5: Deploy UAT site container
- name: Deploy UAT web container
  hosts: uat
  become: true
  vars_files:
    - group_vars/all.secrets.yml
  roles:
    - role: uat_site

# Step 6: Deploy PROD site container (Blue/Green)
- name: Deploy PROD web container
  hosts: prod
  become: true
  vars_files:
    - group_vars/all.secrets.yml
  roles:
    - role: prod_site
