# UAT Infrastructure and Application Deployment

# Step 1: Setup base infrastructure (UAT)
- name: Setup base infrastructure (UAT)
  hosts: uat
  become: true
  vars:
    bootstrap_role: "cloud/oci/bootstrap"  # Full path to bootstrap role
    common_role: "cloud/oci/common"       # Full path to common role
    hardening_role: "cloud/oci/hardening" # Full path to hardening role
    docker_role: "cloud/oci/docker"       # Full path to docker role
    ssh_access_role: "cloud/oci/ssh_access" # Full path to ssh_access role
    jenkins_volume_role: "cloud/oci/jenkins_volume" # Full path to Jenkins volume role
  vars_files:
    - group_vars/all.yml
    - group_vars/all.secrets.yml
    - group_vars/{{ cloud_provider }}/{{ cloud_provider }}.yml
    - group_vars/{{ cloud_provider }}/{{ cloud_provider }}.secrets.yml
  tasks:
    - name: Include bootstrap role
      ansible.builtin.include_role:
        name: "{{ bootstrap_role }}"
      tags: bootstrap

    - name: Include common role
      ansible.builtin.include_role:
        name: "{{ common_role }}"
      tags: common

    - name: Include hardening role
      ansible.builtin.include_role:
        name: "{{ hardening_role }}"
      tags: hardening

    - name: Include docker role
      ansible.builtin.include_role:
        name: "{{ docker_role }}"
      tags: docker

    - name: Include SSH access role
      ansible.builtin.include_role:
        name: "{{ ssh_access_role }}"
      tags: set_ssh_access

    - name: Include Jenkins volume role from provider definition
      ansible.builtin.include_role:
        name: "{{ jenkins_volume_role }}"
      tags: jenkins_volume

# Step 2: Mount Jenkins block volume (provider-specific)
- name: Attach and mount Jenkins block volume
  hosts: uat
  become: true
  tasks:
    - name: Include Jenkins volume role from provider definition
      ansible.builtin.include_role:
        name: "{{ jenkins_volume_role }}"
      tags: jenkins_volume

# Step 3: Setup Jenkins
- name: Setup Jenkins
  hosts: uat
  become: true
  roles:
    - role: jenkins
      tags: jenkins_setup

# Step 4: Deploy UAT web container
- name: Deploy UAT web container
  hosts: uat
  become: true
  roles:
    - role: uat_site
      tags: uat_site