# ansible/uat.yml
---
- name: UAT - Full Infrastructure and App Deployment
  hosts: uat
  become: true

  vars_files:
    - group_vars/all.yml
    - group_vars/all.secrets.yml
    - group_vars/{{ default_provider }}/{{ default_provider }}.yml
    - group_vars/{{ default_provider }}/{{ default_provider }}.secrets.yml

  tasks:
    - name: Re-include cloud-specific vars (in case overridden in secrets)
      ansible.builtin.include_vars:
        file: "group_vars/{{ cloud_provider }}/{{ cloud_provider }}.yml"
      tags:
        - always
        - ssh_access

    - name: Re-include cloud-specific secrets with namespace
      ansible.builtin.include_vars:
        file: "group_vars/{{ cloud_provider }}/{{ cloud_provider }}.secrets.yml"
        name: cloud_secrets
      tags:
        - always
        - ssh_access

    - name: Include bootstrap role
      ansible.builtin.include_role:
        name: "{{ bootstrap_role }}"
      tags: bootstrap

    - name: Include common role
      ansible.builtin.include_role:
        name: "{{ common_role }}"
      tags: common

    - name: Include hardening role
      ansible.builtin.include_role:
        name: "{{ hardening_role }}"
      tags: hardening

    - name: Include docker role
      ansible.builtin.include_role:
        name: "{{ docker_role }}"
      tags: docker

    - name: Include nginx role
      ansible.builtin.include_role:
        name: nginx
      tags: nginx

    - name: Include SSH access role
      ansible.builtin.include_role:
        name: "{{ ssh_access_role }}"
      tags:
        - jenkins        # include it in jenkins runs
        - ssh_access     # still allow running it standalone if needed
        - set_ssh_access # fine-grained override if desired

    - name: Include Jenkins volume mount role
      ansible.builtin.include_role:
        name: "{{ jenkins_volume_role }}"
      tags:
        - jenkins
        - jenkins_volume

    - name: Include Jenkins role
      ansible.builtin.include_role:
        name: jenkins
      tags:
        - jenkins
        - jenkins_tools
        - jenkins_cleanup

    - name: Deploy UAT site container
      ansible.builtin.include_role:
        name: uat_site
      tags: uat_site
